version: 2
jobs:
  build:
    docker:
    - image: githubtraining/ci-custom:latest
    steps:
    - checkout
    - run:
        name: build dependencies
        command: bundle install
    - run:
        name: build the jekyll site
        command: bundle exec jekyll build
    - run:
        name: notify build is finished
        command: echo "The build is finished!"
workflows:
  version: 2
  workflow:
    jobs:
    - build
